### PR TITLE
Symfony 4.2 upgrade

### LINKED ISSUE #86: Symfony 4.2 upgrade
Time to upgrade

### PR DESCRIPTION
**Pull request by jorge07**
Closes #86 & #93

### CODE REVIEW

**Comment by Lutacon** [comment]
I'm trying to debug that deprecated error in tests. Do you get the error only the first time? 🤔

**Comment by Lutacon** [comment]
For this PR to pass, we need some PR to be merged first.

[RabbitMQ-Bundle](https://github.com/php-amqplib/RabbitMqBundle/pull/578)
[NelmioApiDocBundle](https://github.com/nelmio/NelmioApiDocBundle/pull/1457)
[broadway-bundle](https://github.com/broadway/broadway-bundle/pull/57)

**Comment by Lutacon** [comment]
Only one PR to go... 😆

**Comment by zerai** [comment]
update Nelmio to 3.3.1  or latest 3.4.0

**Comment by Lutacon** [comment]
Symfony 4.3 released on friday :trollface:

**Comment by jorge07** [comment]
PRs are welcome :trollface:

**Pull request merged**
