### PR TITLE
mysql version upgrade from 5.7 to 8

### PR DESCRIPTION
**Pull request by kowalk**

### CODE REVIEW

**Comment by jorge07** [comment]
I think we've to tell Doctrine the version too

**Comment by Lutacon** [comment]
Yes. You need to change that line.

https://github.com/jorge07/symfony-4-es-cqrs-boilerplate/blob/master/config/packages/doctrine.yaml#L17

**Comment by kowalk** [comment]
@jorge07 done
@Lutacon thanks for a tip

**Comment by jorge07** [comment]
Just noticed that the k8s chart needs an upgrade too. I'll do this in a separated PR. Thanks @kowalk

**Pull request merged**
