### PR TITLE
PHP 7.3

### PR DESCRIPTION
**Pull request by kowalk**
@jorge07 To build this pull request please merge first changes in Dockerfiles -> https://github.com/jorge07/alpine-php/pull/59

### CODE REVIEW

**Comment by jorge07** [comment]
https://github.com/symfony/symfony/pull/29349/files?

**Comment by kowalk** [comment]
@jorge07 build seems to be green now :) - only some deprecations warning are visible:

```
Unsilenced deprecation notices (17)
Remaining deprecation notices (72)
```
but we can handle that later in https://github.com/jorge07/symfony-4-es-cqrs-boilerplate/pull/88

**Comment by jorge07** [comment]
Is Xdebug working with the new image version? I got seg faults in the past with 2.70apha1

**Comment by jorge07** [comment]
Anyway not related with this PR, this is ready to go. Thanks for the great work @kowalk

**Comment by jorge07** [comment]
Merged 🎉

**Comment by jorge07** [comment]
Closes #90

**Pull request merged**
